package com.sparktechcode.ff.core.common.exceptions;

public enum FFError {
    RESOURCE_NOT_FOUND,
    BAD_REQUEST,
    NOT_FRESH_TOKEN,
    WRONG_CREDENTIALS,
    WRONG_OWNER,
    PERMISSIONS_ERROR,
    USER_ALREADY_EXISTS,
    USER_SUSPENDED,
    USER_REMOVED,
    USER_DEACTIVATED,
    VALIDATION_FAILED,
    UNKNOWN_ERROR,
    CONFLICT
}

